
name: Docker Image CI
description: 'Create package'
inputs:
  commit:
    description: 'git commit sha'
    required: true
    default: 'World'
  version:
    description: 'version number'
    required: true
    default: '0.1'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.commit }}
    - ${{ inputs.version }}

