name: C/C++ CI

on:
  push:
    branches: [ master, github-build-action ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake -DBUILD_SHARED_LIBS=ON
    - name: make
      run: make
    - name: cpack
      run: cpack
