name: Docker Image CI
runs:
  using: 'docker'
  image: 'Dockerfile'

on:
  push:
    branches: [ master, github-build-action ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run:  mkdir /artifacts
    - run:  rpmfile=$(find . -iname "*.rpm"); cp $rpmfile /artifacts
    - run:  debfile=$(find . -iname "*.deb"); cp $debfile /artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: arabica-pkgs
        path: /artifacts


