name: Docker Image CI

on:
  push:
    branches: [ master, github-build-action ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ubuntu-boost:$(date +%s) --tag ubuntu-boost:latest
