name: Main

on:
  push:
    tags:
      - 'release/v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: rpm
      - name: Display structure of downloaded files
        run: ls -R
        #- name: Release
        #uses: softprops/action-gh-release@v1
